### ISSUE TITLE
배포 자동화를 구성한다

### ISSUE THREAD

**Issue by JinJuMoon** [woowacourse-teams/2020-14f-guys#105]
### 제목
- Logging에 대해서 학습한다

### 목적
- 배포, 빌드 과정을 자동화한다

### 상세내용
- 1차 배포 후 진행한다

### 참고

**Comment by ddaaac** [comment]
develop 브랜치에 배포 자동화 완료했습니다.
추후에 jenkins 서버 분리 등을 할 때, 이슈를 다시 열면 좋을 것 같네요
