### ISSUE TITLE
PR review 방법에 대해서 논의한다.

### ISSUE THREAD

**Issue by dks301** [woowacourse-teams/2020-14f-guys#121]
# 목적
- 리뷰와 리뷰 적용의 불편함을 개선하여 빠르게 리뷰와 리뷰적용을 할 수 있다.

# 상세내용
- 리뷰**어**는 가능하면 suggestion을 활용하여 리뷰를 한다.
- 리뷰**이**는 가능하면 수정 사항을 코멘트로 달아준다.

# 참고
내 머리

**Comment by JinJuMoon** [comment]
빠른 개발을 위해 미적용하기로 함
