### ISSUE TITLE
Submodule의 권한을 github personal token을 이용하도록 바꾼다.

### ISSUE THREAD

**Issue by ddaaac** [woowacourse-teams/2020-14f-guys#140]
# 목적

Submodule의 권한을 github personal token을 이용하도록 바꾼다.

# 세부내용

현재는 ssh 키를 사용하는데, 편의성과 보안을 위해 github personal token을 이용하도록 바꾼다.
#120 이슈의 github CI 적용도 가능해진다.

**Comment by dks301** [comment]
Github actions ci는 github secrets값이 fork된 repo의 pr에서는 사용이 불가능하다고 하여 확인이 필요합니다
