### ISSUE TITLE
Submodule 커밋 관리를 올바르게 한다.

### ISSUE THREAD

**Issue by fucct** [woowacourse-teams/2020-14f-guys#147]
# 목적

- Submodule 커밋 관리를 올바르게 한다.

# 세부내용

- 최종 커밋 이전에 `git submodule foreach git commit -a` 과 `git submodule foreach git push` 를 수행한 뒤 , 부모 모듈의 커밋 후 push를 진행한다

**Comment by dks301** [comment]
`git submodule update --remote`로도 가능한거 맞나요 ?

**Comment by KIMSIYOUNG** [comment]
커밋 이전에 항상 submodule을  바로 commit & push 하고, 커밋한다.
