### ISSUE TITLE
s3에 업로드할 때 이미지 format을 jpg로 변환해서 업로드 한다.

### ISSUE THREAD

**Issue by dks301** [woowacourse-teams/2020-14f-guys#219]
# 목적
이미지 파일 크기때문에 성능적인 면에서 좋지 않고 사용자가 사이즈가 큰 이미지를 업로드하면 오류가 발생한다.

# 상세내용
- 이미지파일(bmp, png)을 모두 jpg로 변환하면 압축을 해서 업로드를 할 수 있기때문에 성능적인 이점이 있을 것으로 보입니다.(변환 과정보다는 큰 파일을 통신하는 것이 오버헤드가 큼)

- jpg는 손실 압축이지만 모바일 환경에서는 사이즈를 작게해서 보여주기 때문에 상관이 없을 것으로 보입니다.

# 참고
[](https://blogchannel.tistory.com/269)

**Comment by ddaaac** [comment]
이거 프런트엔드네요
