### ISSUE TITLE
Race와 같이 Member(Column)가 고유해야 하는 도메인에 대해 방어로직을 작성한다.

### ISSUE THREAD

**Issue by fucct** [woowacourse-teams/2020-14f-guys#226]
# 목적

- 프론트의 예외 처리가 미흡하여 동일한 Member에 대해 Race 참여 요청이 2번이 가능해진다.

# 세부내용

- 백엔드 서버 서비스에 방어로직 작성이 필요하다.

# 참고
- 참고1

**Comment by ddaaac** [comment]
다른 곳들에서도 이러한 문제가 일어날 수 있지 않을까요?

**Comment by fucct** [comment]
추가로 Member가 Kakao id 중복 확인도 하여야합니다.
