### ISSUE TITLE
회원 탈퇴 시 오류가 발생한다.

### ISSUE THREAD

**Issue by JinJuMoon** [woowacourse-teams/2020-14f-guys#230]
회원 탈퇴 시 리다이렉트하는 페이지에서 로그인된 멤버의 권한이 필요하기 때문에 오류가 발생한다.
가입화면으로 이동하도록 수정할 필요가 있다.

**Comment by fucct** [comment]
상태도 제거를 해줘야할 것 같네요

**Comment by ddaaac** [comment]
#251
