### ISSUE TITLE
값 객체에 @Value 어노테이션 사용 여부 결정

### ISSUE THREAD

**Issue by fucct** [woowacourse-teams/2020-14f-guys#27]
![image](https://user-images.githubusercontent.com/48818566/87042040-11bb6780-c22e-11ea-9617-5645a77d8499.png)

[레퍼런스 링크](https://projectlombok.org/features/Value)

## 해당 어노테이션이 제공하는 기능
- @Getter
- @FieldDefaults(makeFinal=true, level=AccessLevel.PRIVATE) (기본 필드 접근제어자를 private final 로)
- @AllArgsConstructor
- @ToString
- @EqualsAndHashCode

값 객체에서 사용되는 모든 코드를 포함하고 있어 고려해볼만 하다고 판단됩니다.

**Comment by ddaaac** [comment]
`@FieldDefaults`가 아직 Experimental 단계라서 이 기능은 사용하지 않는 게 좋을 것 같습니다.
그래서 `@Value`를 사용하되 `private final`은 직접 붙이면 좋을 것 같네요!

**Comment by dks301** [comment]
범블비 의견에 동의합니다. 추가로 `@Value `를 통해서 값 객체라는 것을 나타낼 수 있어서 더 좋은 것 같아요 👍

**Comment by KIMSIYOUNG** [comment]
범블비 의견에 동의합니다. 
개인적인 생각으로는 experimental 단계에서 곧 실제 사용이 가능한 형태로 변경될 것 같은데, 그런 경우에도 명시적으로 `private final` 을 작성해주는게 더 나을 것 같습니다. => 변경이 되더라도 우리 코드를 바꾸지 않아도 되면서 @Value 라는 명시적인 의미도 가져갈 수 있기 때문에

**Comment by JinJuMoon** [comment]
저도 범블비 의견에 동의해요~ 다만 Cash의 경우 값이 같아도 같은 객체가 아니기 때문에 `@EqualsAndHashCode`에 대한 고려를 해봐야할 것 같습니다 😄 (@EqualsAndHashCode는 따로 붙여준다던지?)

**Comment by ddaaac** [comment]
값 객체에서는 `@Value`를 사용하고, `private final`을 코드에 직접 붙이는 것으로 하겠습니다~
(ex. Cash)

단, 모든 값이 같다고 같은 객체라고 판단되지 않는 객체의 경우, 사용하지 않는 것으로 하겠습니다.
(ex. RaceTitle)
