### ISSUE TITLE
어도비 XD 및 제플린 사용유무 결정하기

### ISSUE THREAD

**Issue by KIMSIYOUNG** [woowacourse-teams/2020-14f-guys#49]
- 무늬 : 어도비 XD 학습곡선 확인
- 나머지 : 제플린 사용방법 학습

**Comment by fucct** [comment]
- 어도비 XD 사용 결정
- 제플린은 기초 학습 후 결정하기

**Comment by fucct** [comment]
# Zeplin 기능 정리

- 각종 언어의 CSS 로 export 해준다. (Swift, Objective-C, React Native 등..)
- 플랫폼 별로 Size단위를 설정해서 보여줌 (Android는 dp, IOS는 px)
- Font Style, Color Style 등을 그룹화 해서 파일로 export 해줌
- Padding, Margin 등 Space에 대한 정보와 Layout에 대한 정보를 그룹화 해서 export 해줌
- 원하는 컴포넌트를 그룹화해줌 (디자이너가 등록 시)
- 삽입한 이미지(assets)에 대해 1, 2, 3배율 이미지를 export 해주는 기능
- 제플린을 통해 앱, 웹 화면 제공
- 컴포넌트간 거리를 계산할 수 있음

### 단점?

- 디자이너가 디자인 가이드를 제공하는 경우에만 효과적임( 한 명에게 디자인에 대한 업무가 과중될 수 있음)
- 제공하는 기능이 생각보다 한정적임

![image](https://user-images.githubusercontent.com/48818566/87501383-eb685280-c699-11ea-9f2c-19927b394629.png)

**Comment by fucct** [comment]
Adobe XD 사용 결정
제플린 사용 결정
