### ISSUE TITLE
사용하지 않는 브랜치는 삭제하기

### ISSUE THREAD

**Issue by ddaaac** [woowacourse-teams/2020-14f-guys#52]
프로젝트를 진행하다보면 팀원들끼리 fork 한 저장소를 remote에 등록하게 됩니다.
이후 로그를 보면 아래와 같이 나옵니다.
![image](https://user-images.githubusercontent.com/43440195/87489549-47bd7900-c67e-11ea-9c8f-f01931ba9f51.png)

merge가 완료된 브랜치를 지우지 않으면 커밋 그래프에 모두 표시가 됩니다.
아래는 불필요한 브랜치를 삭제한 뒤의 커밋 그래프입니다.
![image](https://user-images.githubusercontent.com/43440195/87490124-cff04e00-c67f-11ea-95f8-1ea518d5de4c.png)

훨씬 깔끔한 그래프가 나오는 것을 확인할 수 있습니다.

github 저장소의 브랜치를 지우는 명령어는 다음과 같습니다.
`git push origin --delete [브랜치명]`

**Comment by KIMSIYOUNG** [comment]
좋은 정보네요! 커밋 줄기?를 간단하게 가져가는게 보기 훨씬 좋네요! 
필요없는 브랜치는 바로바로 삭제해야겠어요!
git branch -D branchname으로도 삭제할 수 있습니다!

**Comment by JinJuMoon** [comment]
모두 삭제했습니다!
