### ISSUE TITLE
이슈 템플릿 적용 관련 논의

### ISSUE THREAD

**Issue by dks301** [woowacourse-teams/2020-14f-guys#79]
이슈 등록할 때 정해져있는 템플릿이 있어서 이에 맞춰서 이슈를 작성하면 좋을 것 같습니다.

**Comment by fucct** [comment]
# 제목
동사로 끝내기

# 목적 
이슈를 통해 얻고자?이루고자 하는 바

# 상세내용
구체적인 설명

# 참고
관련 링크나 참고하면 좋은 사이트 등 공유할 것들
