### ISSUE TITLE
레이스 중간에 레이스 정보를 업데이트 할지 결정해야 한다.

### ISSUE THREAD

**Issue by ddaaac** [woowacourse-teams/2020-14f-guys#99]
현재 레이스의 RaceDuration 필드는 시작일~종료일을 담고 있습니다.
그리고 constraint로 `@FutureOrPresent`를 걸어놨기 때문에 레이스가 시작하고 업데이트를 할 경우 시작일에서 오류가 나게 됩니다.

만약 레이스 중간에 업데이트를 허용하면 `startTime`의 제약 조건을 제거해야 합니다.

**Comment by JinJuMoon** [comment]
Description과 Thumbnail 필드는 변경이 필요할 수도 있겠네요!
